<?php
/** @var $block \Magento\Customer\Block\Account\Customer */
?>
<div class="custom-header-dropdown">
    <button class="dropdown-toggle">
        Account
        <span class="caret">▼</span>
    </button>

    <ul class="dropdown-menu">
        <?php if ($block->customerLoggedIn()): ?>
            <li><a href="<?= $block->getUrl('customer/account') ?>">My Account</a></li>
            <li><a href="<?= $block->getUrl('wishlist') ?>">My Wish List</a></li>
            <li><a href="<?= $block->getUrl('customer/account/logout') ?>">Sign Out</a></li>
        <?php else: ?>
            <li><a href="<?= $block->getUrl('customer/account/login') ?>">Sign In</a></li>
            <li><a href="<?= $block->getUrl('customer/account/create') ?>">Create an Account</a></li>
        <?php endif; ?>
    </ul>
</div>